<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PDFsharp" Version="6.2.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../templates/**/*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>templates/%(RecursiveDir)%(Filename)%(Extension)</Link>
    </None>
  </ItemGroup>

</Project>
